finalapp/urls.py
from django.urls import path
from finalapp import views

app_name = 'finalapp'
urlpatterns = [

        path('',views.dashboard.as_view(),name='profile'),
        path('logout/',views.logout,name='logout'),

        path('list/',views.PostListView.as_view(),name='list'),
        path('<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
        path('post/create/',views.PostCreateView.as_view(),name='create'),
        path('post/update/<int:pk>',views.PostUpdateView.as_view(),name='post_update'),
        path('post/delete/<int:pk>',views.PostDeleteView.as_view(),name='post_delete'),

        path('create/',views.registerUpdateView.as_view(),name='user_create'),
        path('change/password',views.updatePass,name='updatePass'),
        path('update/<int:pk>',views.registerUpdateView.as_view(),name='user_update'),
        path('user/friendz/',views.friends,name='friends'),
        path('user_inbox/',views.user_inbox,name='user_inbox'),
        path('user/messages',views.message_list.as_view(),name='message_list'),

        path('user/ajax/message/',views.save_message_ajax,name='ajax_message'),
        path('user/inbox/all/',views.show_message_all,name='show_message'),
        path('user/name/ajax',views.ajax_fun,name='ajax_fun'),
        path('user/profile',views.userProfile,name='user_profile'),
        path('user/newsfeed',views.news_feed,name='news_feed'),
        path('user/feed/description',views.feed_description, name='feed_description'),




]

finalproject/urls.py
from django.contrib import admin
from django.urls import path,include
from finalapp import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('users',views.users,name='users'),
    path('users/follow/',views.follow,name='follow'),
    path('post/like/',views.postlike,name='like'),
    path('finalapp/',include('finalapp.urls',namespace='finalapp')),

    # path('login/', views.user_login,name='login'),
    # path('logout/',views.ulogout,name ='logout'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/change_password.html
{% extends "dashboard.html" %}
{% block body_block %}
    
{% load staticfiles %}
{% load bootstrap4 %}

    <div class ="container bg-secondary">
      <div class="row">
        <div class="col-md-12 mx-auto bg-light px-4">
          <h4 class=' display-4 alert alert-primary text-center my-3'>Change Password for user <span class='text-danger'> {{user}}</span> </h4>
            <div class='row'>
                <div class='col-md-4 mx-auto p-2 bg-danger'>
                        <form action="" method='post' class='p-4 bg-light'>
                                {% csrf_token %}
                                <div class='form-group'>
                                    <input type="password" class='form-control' name='op' placeholder='Old Password'/>
                                </div>
                                <div class='form-group'>
                                        <input type="password" class='form-control' name='n1' placeholder='New Password'/>
                                </div>
                                <div class='form-group'>
                                    <input type="password" class='form-control' name='n2' placeholder='Re-enter New Password'/>
                                </div>
                                <div class='form-group'>
                                    <input type="submit" class='btn btn-primary' placeholder='Old Password'/>
                                </div>
                
                            </form>
                </div>
            </div>
        </div>
      </div>
    </div>
{% block form %}

{% endblock %}
{% endblock %}

templates/dashboard.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap4 %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "fontawesome/css/all.css"%}">
    <script src='{% static "jquery.js" %}'></script>
    <script src='{% static "bootstrap/js/bootstrap.js" %}'></script>
    {% block mycss %}

    {% endblock %}
    <style media="screen">
    html, body{
      height:100%;
    }
    .ab:hover{
      box-shadow:10px 10px 8px #ccc;
      height:110px;
      width:110px;
      border-radius:50%;
    }
    .menu{
      padding-top:2 0%;
      text-decoration: none;
    }
    .container-fluid{
      height:100% !important;
    }
    .ab{
      transition: rotate(90deg);
    }

    .right {
  position: relative;
  background: #fce3e3;
  text-align: right;
  min-width: 45%;
  padding: 10px 15px;
  border-radius: 6px;
  border: 1px solid #ccc;
  float: right;
  right: 20px;
}

.right::before {
  content: '';
  position: absolute;
  visibility: visible;
  top: -1px;
  right: -10px;
  border: 10px solid transparent;
  border-top: 10px solid #ccc;
}

.right::before {
  content: '';
  position: absolute;
  visibility: visible;
  top: 0px;
  right: -8px;
  border: 10px solid transparent;
  border-top: 10px solid #fce3e3;
  clear: both;
}


/* .left {
position: relative;
background: white;
text-align: right;
min-width: 45%;
padding: 10px 15px;
border-radius: 6px;
border: 1px solid #ccc;
float: right;
right: 20px;
}

.left::after {
content: '';
position: absolute;
visibility: visible;
top: -1px;
right: -10px;
border: 10px solid transparent;
border-top: 10px solid #ccc;
}

.left::before {
content: '';
position: absolute;
visibility: visible;
top: 0px;
left: -8px;
border: 10px solid transparent;
border-top: 10px solid white;
clear: both;
} */

.dblockonsmall{
  display: none;
}
@media screen and (max-width:600px){
  .dblockonsmall{
    display: block;
  }
  .dnoneonsmall{
    display: none;
  }
}
    </style>
  </head>
  <body  style='background-image:url(""); background-size:100% 100%; height:100%;'>
    <div class="container-fluid" style='height:100%;'>
      <div class="row">
        <div class="col-md-12 dnoneonsmall">
          <nav class='navbar navbar-expand-sm fixed-top navbar-dark bg-primary d' style='background:rgba(0,0,0,0.7)'>
            <a href="#" class='navbar-brand text-white'>Friends Zone
              <i class="fas fa-comments"  style="font-size:40px; color:white"></i>
            </a>
            <ul class='navbar-nav ml-auto'>
              <li class='nav-item'>
                <a href="{% url "finalapp:profile"%}" class='nav-link active text-white'> <i class="fas fa-home"></i> </a>
              </li>
              <li class='nav-item'>
                <a href="{% url "finalapp:news_feed"%}" class='nav-link active text-white'> <i class="fas fa-newspaper"></i> </a>
              </li>
              <li class='nav-item'>
                <a href="{% url "finalapp:list"%}" class='nav-link active text-white'> <i class="fas fa-paste"></i> </a>
              </li>
              <li class='nav-item'>
                <a href="{% url "finalapp:create"%}" class='nav-link text-white'> <i class="fas fa-notes-medical"></i> </a>
              </li>
              <li>
                <li class='nav-item'>
                  <a href="{% url "finalapp:friends" %}" class='nav-link text-white'> <i class="fas fa-envelope"></i> </a>
                </li>
                <li class='nav-item'>
                  <a href="#" class='btn btn-outline-light' > Welcome {{ user.username|upper }} !</a>
                </li>
            </ul>
          </nav>
      </div>
    </div>
    <div style="height:67px;" class='dnoneonsmall'>
    </div>
    <div class="row">
      <!-- EX START -->
      <div class="col-md-3 px-0 dblockonsmall">
          <nav class="navbar navbar-expand-md bg-info navbar-dark">
              <!-- Brand -->
              <a href="#" class='navbar-brand text-white'>Friends Zone <i class="fas fa-comments"  style="font-size:40px; color:white"></i></a>
              <!-- Toggler/collapsibe Button -->
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
              </button>
              <!-- Navbar links -->
              <div class="collapse navbar-collapse" id="collapsibleNavbar">
                  {% for i in userp %}
                  <div class="row">
                    <div class="col-md-12 text-center py-3">
                      <img src="/media/{{ i.profile_pic }}" style="width:100px; height:100px; border-radius:50%;"/>
                        <h4 class="text-white">{{ user.username|upper }}</h4>
                    </div>
                  </div>
                  <ul class="navbar-nav">
                    <li class='nav-item'>
                      <a href="{% url "finalapp:profile"%}" class='nav-link'><i class="fas fa-home"></i> Dashboard</a>
                    </li>
                    
                    <li class="nav-item">
                          <a href="{% url "finalapp:user_update" pk=i.id %}" class='nav-link'><i class="fas fa-user-circle"></i> Edit Profile</a>
                      </li>
                      <li class="nav-item">
                        <a href="{% url "finalapp:user_profile" %}" class='nav-link'><i class="far fa-user-circle"></i>  View Your Profile</a> 
                      </li>
                      <li class="nav-item">
                        <a href="{% url "finalapp:updatePass" %}" class='nav-link'><i class="fas fa-key"></i> Change Password</a>
                      </li>
                      <li class="nav-item">
                        <a href="{% url "finalapp:friends"%}" class='nav-link'><i class="fas fa-user-friends"></i> Friends</a> 
                      </li>
                      <li class='nav-item'>
                        <a href="{% url "finalapp:news_feed"%}" class='nav-link'><i class="fas fa-newspaper"></i>News Feed </a>
                      </li>
                      <li class='nav-item'>
                        <a href="{% url "finalapp:list"%}" class='nav-link'><i class="fas fa-paste"></i> Your posts</a>
                      </li>
                      <li class='nav-item'>
                        <a href="{% url "finalapp:create"%}" class='nav-link'><i class="fas fa-notes-medical"></i> Create Post</a>
                      </li>
                      <li class="nav-item">
                        <a href="{% url "finalapp:friends" %}" class='nav-link'><i class="fas fa-envelope-square"></i>Messages</a> </li>
                      <li class="nav-item">
                         <a href="{% url "finalapp:logout"%}" class='nav-link'><i class="fas fa-sign-out-alt"></i>Logout</a> </li>
                    </ul>
                {% endfor%}
              </div> 
            </nav> 
      </div>
      <!-- EX END HERE -->
      <div class="col-md-3 bg-dark dnoneonsmall">
          <div class="row pt-5">
            <div class="col-md-8 ">
                {% for i in userp %}
            <a href="/media/{{i.profile_pic}}">
              <div class='mx-auto ab' style="height:100px ; width:100px; border-radius:100px; background:url('/media/{{ i.profile_pic }}'); background-size:100% 100%;"></div>
              </a>
              
                <ul class="text-light" style='list-style-type:none;'>

                  <li class="menu"><i class="fas fa-user-circle mr-2"></i>  <a href="{% url "finalapp:user_update" pk=i.id %}"> Edit Profile</a></li>

                  <li class="menu"><i class="far fa-user-circle mr-2"></i> <a href="{% url "finalapp:user_profile" %}">View Your Profile</a> </li>
                  <li class="menu"><i class="fas fa-key mr-2"></i> <a href="{% url "finalapp:updatePass" %}"> Change Password</a></li>
                  <li class="menu"><i class="fas fa-user-friends mr-2"></i> <a href="{% url "finalapp:friends"%}">Friends</a> </li>
                  <li class='menu'>
                    <a href="{% url "finalapp:news_feed"%}" class=' '><i class="fas fa-newspaper text-white  mr-2"></i>News Feed </a>
                  </li>
                  <li class='menu'>
                    <a href="{% url "finalapp:list"%}" class=''> <i class="fas fa-paste text-white mr-2"></i> Your posts</a>
                  </li>
                  <li class='menu'>
                    <a href="{% url "finalapp:create"%}" class=''> <i class="fas fa-notes-medical text-white mr-2 "></i> Create Post</a>
                  </li>
                  <li class="menu"><i class="fas fa-envelope-square mr-2"></i> <a href="{% url "finalapp:friends" %}">Messages</a> </li>
                  <li class="menu"><i class="fas fa-sign-out-alt mr-2"></i> <a href="{% url "finalapp:logout"%}">Logout</a> </li>
                </ul>{% endfor %}
              </div>

            </div>
        </div>
  <div class='col-md-9 bg-light py-3'>
    {% if u %}
    <h4 style='font-family:cursive;'>People You May Know</h4>
    {% endif %}

    <div class="card-columns py-4">
        {% for i in p %}
      <div class="card text-center pt-4">
        <div class="card-head">
          <div style="text-align:center;">
            {% if i.profile_pic %}
            <img src="/media/{{ i.profile_pic }}" class='ab' alt="No Image" height='100' width='100' style='border-radius:50%;'>
            {% else %}
            <img src="{% static "images/no_img.jpg"%}" alt="No Image" height='100' width='100' style='border-radius:50%;'>
            {% endif %}
          </div>

          <h2 class='card-title text-center'> {{ i.username}}</h2>
          <small class='card-text'>Date Joined: {{ i.registered_id}}</small><br/>
          <a href="{% url "follow"%}?id={{i.user_id}}" class="{{ i.btn1 }}">{{ i.btn}}</a>
          <!-- {% if i.btn %}
          <a href="{% url "follow"%}?id={{i.user_id}}" class="btn btn-warning">Unfollow</a>
          {% else %}
          <a href="{% url "follow"%}?id={{i.user_id}}" id='{{i.id}}' class="btn btn-success">Follow</a>
          {% endif%} -->
          <!-- <a href="{% url "follow"%}?id={{i.user_id}}" class="btn btn-danger">Delete</a> -->

        </div>
        <div class="card-body">

        </div>
      </div>
      {% endfor %}
    </div>
    {% block body_block %}

    {% endblock %}

  </div>
</div>

    </div>

  </body>
</html>

templates/facebook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Facebook</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"/>
    <style>
        .header{
            background:#3b5998;
            font-family:Arial;
            text-align:center;
            cursor: pointer;
            
        }
        .head{
            font-weight:bolder;
            }
        .pA{
            text-align:center;
            background: #fcfbcc;
            color:#3b5998;
            cursor: pointer;
        }
        .inp{
            padding:22px;
            box-shadsow:none;
            
        }
        textarea:focus,
textarea.form-control:focus,
input.form-control:focus,
input[type=text]:focus,
input[type=password]:focus,
input[type=email]:focus,
input[type=number]:focus,
[type=text].form-control:focus,
[type=password].form-control:focus,
[type=email].form-control:focus,
[type=tel].form-control:focus,
[contenteditable].form-control:focus {
  box-shadow: inset 0 -1px 0 #ddd;
}
body{
    cursor: pointer;
}
.tn{
    text-decoration:none;
}
    </style>
</head>
<body>
    <div class='container-fluid' style='background:#e6e9ef'>
        <div class='row'>
            <div class='col-md-12 text-white header'>
                <h2 class='head pt-1'>facebook</h2>
            </div>
            <div class='col-md-12 pA py-2'>
                <a href="https://play.google.com/store/apps/details?id=com.facebook.katana&hl=en" style='text-decoration:none; color:#3b5998;'>
                    <i class="fas fa-mobile-alt " style='font-size:25px;'></i><span style=''> Get Facebook for Android and browser faster.</span>
                </a>
            </div>
        </div>
        <div class='row'>
            <div class='col-md-4 mx-auto p-3'>
                <form action="">
                    <div class='form-group'>
                            <input type="text" class='form-control border-bottom-0 inp' placeholder='Mobile number or email address'>
                            <input type="password" class='form-control inp' placeholder='Password'>
                    </div>
                    <div class='form-group'>
                        <input type="submit" class='btn btn-block btn-primary font-weight-bold' value='Log In'>
                    </div>
                </form>
                <div class="row">
                    <div class='col-5'>
                        <hr/>
                    </div>
                    <div class='col-2 text-center'>
                        <span>or</span>
                    </div>
                    <div class='col-5'>
                        <hr/>
                    </div>
            </div>
            <div class=row>
                <div class='col-md-12 mx-auto text-center pb-4'>
                    <h2 class='btn btn-success font-weight-bold' style='background: #00a400;'>Create New Account</h2><br/>
                     <a class='tn' style='text-decoration:none;' href="https://m.facebook.com/login/identify/?ctx=recover&c=https%3A%2F%2Fm.facebook.com%2F&multiple_results=0&ars=facebook_login&lwv=101&_rdr"> <small style='color:#7596c8;'>Forgotten Password? </a>. <a href="https://m.facebook.com/help/?refid=8" style='text-decoration:none;' class='tn'> Help  Centre</small></a>
                </div>
            </div>
            </div>
        </div>
    </div>
    <div class='text-center'>
        <small class='text-secondary py-2'>Facebook &copy; 2018</small>

    </div>
</body>
</html>

templates/feed_description.html
{% extends "dashboard.html"%}
{% load staticfiles %}
{% block body_block %}
{% if postdict.img %}
<div class="row py-5" style='background: url("/media/{{postdict.img}}");background-size:100% 100%;'>
  {% endif %}
  <div class="col-md-12 py-5 text-center">
    <h1 class=' py-3 text-white font-weight-bold' style='font-family:arial; background:rgba(0,0,0,0.5)'>{{postdict.title}}</h1>
  </div>
</div>
  <div class='container text-center py-2'>
    <div class='row'>
        <div class='col-md-12 bg-white mb-2'>
            <p>{{postdict.text}}</p>
            <span class='text-secondary float-right'> On {{postdict.create}}</span>
          </div>
      <div class="col-md-12">
        <form method="post">
          {% csrf_token %}
          <div class="form-group">
            <div class="row">
              <div class="col-md-10">
                <textarea name="com" rows="4" width='50%' placeholder='Type comment here ...' class='form-control'></textarea>
              </div>
              <div class="col-md-2">
                <input type="submit" class='btn-info btn-block py-2 border-0' name="" value="Comment">
              </div>
            </div>
          </div>
        </form>
      </div>

      <div class='col-md-12 text-left'>
        <p style='font-family:cursive;'>Total Comments : {{total}}  Likes {{tl}}</p>
        <ul class='cmt list-group'>
          {% for i in comm%}
            <li class='list-group-item'>  <p class='text-primary' style='font-family:cursive;'>

                  {% if i.commenterid.profile_pic %}
                  <img src="/media/{{i.commenterid.profile_pic}}" style='border-radius:50%;' height=50 width=50 alt="">
                {% else %}
                <img src="{% static 'images/no_img.jpg'%}" style='border-radius:50%;' height=50 width=50 alt="">
                {% endif %}

                  {{i.commenterid.user.username}}</p>
                  <p>{{i.comment}}</p> </li>


          {% endfor %}

        </ul>
      </div>
    </div>
  </div>

{% endblock %}

templates/friends.html
{% extends "dashboard.html" %}
{% block mycss %}
  <style media="screen">
    .ab:hover{
      box-shadow:10px 10px 8px #ccc;
      height:45;
      width:45;
      border-radius:50%;
    }
  </style>
{% endblock %}
<div class="container">
{% block body_block %}
  <div class="row">
    <div class="col-md-12">
      <h4 style='font-family:cursive'>Total Friends: {{total}}</h4>
      <ul class='list-group'>
        {% for i in friendList %}
        <li class="list-group-item">
          <div class="row">
            <div class="col-md-2">
              <a href="/media/{{i.pp}}"> <img src="/media/{{i.pp}}" class=' ab rounded-circle' alt="No Image" height=40 width=40></a>
            </div>
            <div class="col-md-4">
              <p class='text-primary'  style=''>{{i.un}}</p>

            </div>
            <div class="col-md-6">
              <a href="{% url "follow"%}?id={{i.id}}" class="mx-2 text-danger" title='Unfollow'><i class="far fa-times-circle" style='font-size:30px;'></i></a>
              <a href="{% url 'finalapp:user_inbox'%}?id={{i.id}}" class='' titile=/messafe><i class="fab fa-facebook-messenger" style='font-size:30px;'></i></a>
            </div>
          </div>
        </li>
        {% endfor %}
      </ul>

    </div>
  </div>
</div>
{% endblock %}

templates/inbox.html
{% extends "dashboard.html" %}
{% load staticfiles %}
{% block mycss %}
  <style>
    .chat{
      height:30px;
      width:30px;
      background: #ccc;
      position:absolute;
      left:-7px;
      top:7px;
      transform: rotate(45deg);
    }
  </style>
{% endblock %}
{% block body_block %}
<div class="row">
  <div class="col-md-12 text-center">
    <img src="/media/{{det.profile_pic}}" alt="No Image" height="100" width="100" style='border-radius:50%;' />
    
    <h1>{{det.name}}</h1>
    <small>Active on : {{det.lastlogin}}</small><br/>
    <small>Born on : {{det.dob}}</small>
    <hr />
    <div class="row">
      <div class="col-md-12 text-left">
        <div class="bg-secondary p-3">
        <label>Send Message</label>
        {% csrf_token %}
        <textarea class="form-control" placeholder="Enter Your Message Here" id='msg'></textarea>
        <input type="button" class="btn btn-success mt-3" id='msgbtn' value="Send" />
        </div>
        <ul class="list-group aaa">
          
          <li class="list-group-item text-right">
              <small>Name</small><br/>
              MSG1<br/>
              <small>Received @ : Time</small>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
  <script>
  $(function(){
    $('#msgbtn').click(function(){
      var a = $('#msg').val();
      var sendto = "{{ det.sendto }}";
      var sndr = "{{det.loginuser}}";
      var b = $("input[name*='csrfmiddlewaretoken']").val();
      $.ajax({
        url: '{% url "finalapp:ajax_message" %}',
        type: 'post',
        data: {rcvr:sendto,message:a, csrfmiddlewaretoken:b},
        success: function(data){
          // alert(data);
          getMsg();
        }
      })
    });
  });
  function getNameFromId(id){
    var b = $("input[name*='csrfmiddlewaretoken']").val();
    var ss = '';
    $.ajax({
      url: '{% url "finalapp:ajax_fun"%}',
      type: 'POST',
      async: false,
      data: {usernamefromid:id, csrfmiddlewaretoken:b},
      success: function(data){
        ss = data;
      }
    });
    return ss;
  }
  function getMsg(){
    var sendto = "{{ det.sendto }}";
    var sndr = "{{det.loginuser}}";
    var b = $("input[name*='csrfmiddlewaretoken']").val();
    var alignment = "";
    $.ajax({
      url : '{% url "finalapp:show_message" %}',
      type: 'POST',
      data: { sndr:sndr, rcvr:sendto ,csrfmiddlewaretoken:b},
      success: function(data){
        var a = '';
        for(n in data){
          if(sndr==data[n].fields.sender){
            alignment = "text-left";
          }else{
            alignment = "text-right bg-light";
          }
          a += "<li class='list-group-item "+alignment+"'><small><strong>"+getNameFromId(data[n].fields.sender)+"</strong></small><br/>";
          a += data[n].fields.message+"<br/><small class='text-muted'>"+data[n].fields.created_at+"</small></li>";
        }
        $('.aaa').html(a);
      }
    });
  }
  setInterval(getMsg, 5000);
  getMsg();
  </script>
{% endblock %}

templates/newsfeed.html
{% extends "dashboard.html"%}
{% block body_block %}
        <div class='row'>
            <div class='col-12 card-columns'>
                {% for i in posts %}
                <div class='card'>
                    <div class='card-header text-center' style='width:100%;'>
                    {% if i.author.username is user.username %}
                    <h4 class='text-primary' style='font-family:cursive'>You</h4>
                    {% else %}
                    <h4 class=' text-primary' style='font-family:cursive'>{{i.author.username}}</h4>
                    {% endif %}
                    {% if i.author.first_name %}
                    <small class=''>( {{i.author.first_name}} {{ i.author.last_name }} )</small><br/>
                    {% endif %}
                         <img src="/media/{{i.image}}" alt="" height=200 width=100%>
                    </div>
                    <div class='card-body'>
                        <h5 class='' style='font-family:Gill Sans'> {{i.title}}<a href="{% url "finalapp:feed_description"%}?id={{i.id}}" class='btn btn-sm btn-primary float-right'><i class='fas fa-eye'></i> View Post</a></h5>

                        <p>{{i.text}}</p>
                        <small class=' text-primary'>
                          <a href="{% url "finalapp:feed_description"%}?id={{i.id}}">
                          <i class="far fa-comments" style='font-size:20px;'></i>
                          {% if i.comments %}
                           {{i.comments}}
                          {% else %}
                          0{%endif%}
                          </a>
                          <a href="{% url "like"%}?id={{i.id}}" class="">
                            <i class="fas fa-thumbs-up"></i>
                              {% if i.likes%}
                              {{i.likes}}
                            {% else%}
                          0{% endif %}
                          </a>


                          <span class='float-right'><i class="far fa-clock"></i> {{i.create_date }}</span></small>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
{% endblock %}

templates/registration_form.html
{% load staticfiles %}
{% load bootstrap4 %}

    <div class ="container bg-secondary">
      <div class="row">
        <div class="col-md-6 mx-auto bg-light px-4 my-5">
          <h1 class='alert alert-primary text-center my-3'>Registeration Form</h1>
          {{al}}
        </div>
      </div>
    </div>
{% block form %}

{% endblock %}

templates/userprofile.html
{% extends "dashboard.html"%}
{% block mycss %}
<style media="screen">
  td{
    /* text-align:right; */
  }
</style>
{% endblock %}
{% block body_block %}
  <div class="row">
    <div class="col-md-12 text-center">
      <img src="/media/{{profile.profile_pic}}" alt="No Image" height=150 width=150 style='border-radius:50%'>
      <h2 class='' style='font-family:cursive'>{{profile.first_name}} {{profile.last_name}}</h2>
      <a href="{% url "finalapp:user_update" pk=profile.id %}" class='btn btn-primary'>Edit Profile</a>
      <hr/>
    </div>
  </div>
    <div class="row">
      <div class="col-md-12">
        <table class='table table-hover' style='width:100%;'>
          <tr>
            <th>Username</th>
            <td>{{profile.username}}</td>
            </tr>
            <tr>
              <th>Email</th>
              <td>{{profile.email}}</td>
            </tr>
            <tr>
              <th>First Name</th>
              <td>{{profile.first_name}}</td>
            </tr>
            <tr>
              <th>Last Name</th>
              <td>{{profile.last_name}}</td>
            </tr>
            <tr>
              <th>Gender</th>
              <td>{{profile.gender}}</td>
            </tr>
            <tr>
              <th>Worked At </th>
              <td>{{profile.work}}</td>
            </tr>
            <tr>
              <th>Interests</th>
              <td>{{profile.interests}}</td>
            </tr>
            <tr>
              <th>Status</th>
              <td>{{profile.status}}</td>
            </tr>
            <tr>
              <th>DOB</th>
              <td>{{profile.dob}}</td>
            </tr>
            <tr>
              <th>Education</th>
              <td>{{profile.education}}</td>
            </tr>
            <tr>
              <th>About</th>
              <td>{{profile.about}}</td>
            </tr>
            <tr>
              <th>Current City</th>
              <td>{{profile.current}}</td>
            </tr>
            <tr>
              <th>HomeTown</th>
              <td>{{profile.home}}</td>
            </tr>
            <tr>
              <th>Registered</th>
              <td>{{profile.registered}}</td>
            </tr>

          </table>
      </div>
    </div>

{% endblock %}

templates/users.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

  </head>
  <body>
    {{ u }}
    <table>
      <thead>
        <tr>
          <th>Username</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Action</th>
        </tr>
      </thead>
    {% for i in u %}
      <tr>
        <td>{{i.user.username}}</td>
        <td>{{i.user.first_name}}</td>
        <td>{{i.last_name}}</td>
        <td>{{i.user.email}}</td>
        <td>{{i.profile_pic}}</td>
        <td>{{i.gender}}</td>


        <td><button>Click</button></td>
      </tr>
    {% endfor %}
    </table>
  </body>
</html>