finalapp/urls.py
from django.urls import path
from finalapp import views

app_name = 'finalapp'
urlpatterns = [

        path('',views.dashboard.as_view(),name='profile'),
        path('logout/',views.logout,name='logout'),

        path('list/',views.PostListView.as_view(),name='list'),
        path('<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
        path('post/create/',views.PostCreateView.as_view(),name='create'),
        path('post/update/<int:pk>',views.PostUpdateView.as_view(),name='post_update'),
        path('post/delete/<int:pk>',views.PostDeleteView.as_view(),name='post_delete'),

        path('create/',views.registerUpdateView.as_view(),name='user_create'),
        path('change/password',views.updatePass,name='updatePass'),
        path('update/<int:pk>',views.registerUpdateView.as_view(),name='user_update'),
        path('user/friendz/',views.friends,name='friends'),
        path('user_inbox/',views.user_inbox,name='user_inbox'),
        path('user/messages',views.message_list.as_view(),name='message_list'),

        path('user/ajax/message/',views.save_message_ajax,name='ajax_message'),
        path('user/inbox/all/',views.show_message_all,name='show_message'),
        path('user/name/ajax',views.ajax_fun,name='ajax_fun'),
        path('user/profile',views.userProfile,name='user_profile'),
        path('user/newsfeed',views.news_feed,name='news_feed'),
        path('user/feed/description',views.feed_description, name='feed_description'),




]

finalproject/urls.py
from django.contrib import admin
from django.urls import path,include
from finalapp import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('users',views.users,name='users'),
    path('users/follow/',views.follow,name='follow'),
    path('post/like/',views.postlike,name='like'),
    path('finalapp/',include('finalapp.urls',namespace='finalapp')),

    # path('login/', views.user_login,name='login'),
    # path('logout/',views.ulogout,name ='logout'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalapp/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.utils import timezone
from django.urls import reverse
class register(models.Model):
    GENDER = [('male','male'),
            ('female','female')]

    M_STATUS = [('Married ','Married '),
            ('engased ','engased '),
            ('commited ','commited '),
            ('Widowed ','Widowed '),
            ('Separated ','Separated '),
            ('Divorced ','Divorced '),
            ('Single ','Single '),
            ("It's complicated","It's complicated"),
            ("other","other"),]

    INTERESTS= [('men','men'),
            ('women','women'),
            ('both','both')]

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    date_of_birth= models.DateField(null=True)
    gender = models.CharField(choices=GENDER,max_length = 200,default='female')
    profile_pic = models.FileField(null=True,blank=True, upload_to = 'profile/%Y/%m/%d')
    # Additional Fields
    current_city = models.CharField(null=True,max_length=250,blank=True)
    hometown = models.CharField(null=True,max_length=250,blank=True)
    education_details =models.CharField(null=True,max_length=250,blank=True)
    interested_in = models.CharField(choices=INTERESTS,null=True,max_length=250,blank=True)
    marital_status = models.CharField(choices=M_STATUS, null=True,max_length=250,blank=True)
    worked_at = models.CharField(null=True,max_length=250,blank=True)
    about_you = models.TextField(blank=True, null=True)
    registered_at = models.DateTimeField(auto_now_add = True,null=True)


    def __str__(self):
        return self.user.username
    # def get_absolute_url(self):
    #     return reverse('user_update', kwargs={'pk': self.pk})

class Post(models.Model):
    author = models.ForeignKey(User,on_delete= models.CASCADE)
    title = models.CharField(max_length=250)
    image = models.FileField(null=True, upload_to = 'post/%Y/%m/%d')
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now())
    published_date = models.DateTimeField(blank = True,null = True)
    comments = models.IntegerField(null=True)
    likes =models.IntegerField(null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    def get_absolute_url(self):
        return reverse('finalapp:post_detail',kwargs={'pk':self.pk})


    def __str__(self):
        return self.title


class Message(models.Model):
    name=models.CharField(max_length=20)
    email=models.EmailField(max_length=50)
    message=models.CharField(max_length=20)

class followUsers(models.Model):
    follower = models.IntegerField()
    following = models.IntegerField()
    create_date = models.DateTimeField(auto_now_add = True)
    is_friend = models.BooleanField(default=False)

    def __str__(self):
        return repr(self.follower)

    class Meta():
        verbose_name_plural="Follower Table"

class inbox(models.Model):
    sender=models.IntegerField()
    receiver = models.IntegerField()
    message=models.TextField()
    status=models.BooleanField(default=False)
    approved =models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message

class postcomment(models.Model):
    postid = models.IntegerField()
    commenterid = models.ForeignKey(register,on_delete=models.CASCADE,null=True)
    comment = models.TextField()
    create_date = models.DateTimeField(auto_now_add = True)
    aproved= models.BooleanField(default=False)

    def __str__(self):
        return repr(self.postid)

class likes(models.Model):
    follower = models.IntegerField()
    postid = models.IntegerField()
    create_date = models.DateTimeField(auto_now_add = True)
    is_like = models.BooleanField(default=False)

    def __str__(self):
        return repr(self.follower)

    class Meta():
        verbose_name_plural="Like Table"

finalapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import register
class registerForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())
    def clean(self):
        clean_data=super().clean()
        pwd = clean_data['password']
        cpwd= clean_data['confirm_password']
        if pwd != cpwd:
            raise forms.ValidationError("Password Does Not Match")
    class Meta():
        model=User
        fields=('first_name','last_name','username','email','password')

class registerForm2(forms.ModelForm):
    GENDER = [('male','male'),
            ('female','female')]
    date_of_birth= forms.CharField(widget=forms.TextInput(attrs={'type':'date','help_text':'Date Of Birth'}))
    gender = forms.ChoiceField(choices=GENDER,widget=forms.RadioSelect())
    class Meta():
        model = register
        fields = ('date_of_birth','gender','profile_pic')

finalapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import registerForm,registerForm2
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout as logout_view
from django.views.generic import TemplateView,ListView, DetailView,CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, register,followUsers,inbox, postcomment, likes, Message
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django import forms
from django.core import serializers
# Create your views here.
def index(request):
    form=registerForm()
    form1 = registerForm2()
    if request.method == 'POST':
        if "register" in request.POST:
            form = registerForm(data=request.POST)
            form1 = registerForm2(request.POST,request.FILES)

            if form.is_valid() and form1.is_valid():
                user = form.save()
                user.set_password(user.password)
                user.save()

                frm2 = form1.save(commit=False)
                frm2.user = user

                if "profile_pic" in request.FILES:
                    frm2.profile_pic = request.FILES['profile_pic']
                    print("Success")
                frm2.save()
                register = "register Successfully"
                return render(request,'index.html',{'rf':form,'rf2':form1,'rg':register})

            else:
                print(form1.errors,form.errors)
                register = ("OOPs!! Could Not Register!! Try Again!!!")
                return render(request,'index.html',{'rf':form,'rf2':form1,'rg':register})


        elif "login" in request.POST:
            print("login Button")
            usern = request.POST['un']
            passw = request.POST['pwd']
            user = authenticate(username = usern, password = passw)
            if user:
                print("Hello")
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect('/finalapp')
                else:
                    register="You are not active user!!!"
                    return render(request,'index.html',{'rf':form,'rf2':form1,'rg':register})
            else:
                register="Could not login !!! You are not Registered User!!!"
                return render(request,'index.html',{'rf':form,'rf2':form1,'rg':register})
        
        elif "feedbtn" in request.POST:
            name = request.POST['feedname']
            email = request.POST['feedemail']
            msz = request.POST['feedmessage']
            feedback = Message(name = name, email= email, message=msz)
            feedback.save()
            register = "Thanks for your Anonymous Feedback!!!"
            return render(request,'index.html',{'rf':form,'rf2':form1,'rg':register})

    data = User.objects.order_by('-id')[:5]
    for ab in data:
        print(ab)
    return render(request,'index.html',{'rf':form,'rf2':form1,'dt':data})
def registeration(request):
    return render(request,'registration_form.html',{'rf':form})

class dashboard(LoginRequiredMixin,TemplateView):
    template_name="dashboard.html"
    def get_context_data(self,*args,**kwargs):
        loginid = self.request.user.id
        data=super().get_context_data(*args,**kwargs)
        data['u'] = register.objects.exclude(user_id = loginid)
        data['userp'] = register.objects.filter(user_id = loginid)
        friend_ll = []
        for i in data['u']:
            myd = {}
            if followUsers.objects.filter(follower=loginid, following=i.user.id, is_friend=True):
                myd['btn'] = 'Unfollow'
                myd['btn1'] = 'btn btn-danger'
            else:
                myd['btn'] = 'Follow'
                myd['btn1'] = 'btn btn-warning'
                myd['username'] = i.user.username
                myd['profile_pic'] = i.profile_pic
                myd['registered_id'] = i.registered_at
                myd['user_id'] = i.user.id
                friend_ll.append(myd)
        data['p'] = friend_ll
        # print(data['p'])
        success_url = reverse_lazy('finalapp:profile')
        return data
class PostListView(ListView):
    model = Post
    # success_url =reverse_lazy("cbvapp:list")

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['post_list'] = Post.objects.filter(author=self.request.user.id)
        context['userp'] = register.objects.filter(user_id = self.request.user.id)
        print(context)
        return context

class PostDetailView(DetailView):
    model = Post
    context_object_name = "post_detail"
    template_name = 'finalapp/post_detail.html'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['userp'] = register.objects.filter(user_id = self.request.user.id)
        return context

class PostUpdateView(UpdateView):
    model = Post
    fields=['title','image','text']

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['userp'] = register.objects.filter(user_id = self.request.user.id)
        return context

class PostDeleteView(DeleteView):
    model = Post
    success_url =reverse_lazy('finalapp:list')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['userp'] = register.objects.filter(user_id = self.request.user.id)
        return context

class PostCreateView(LoginRequiredMixin,CreateView):
    context_object_name='create'
    model=Post
    fields=('title','image','text')
    # success_url = reverse_lazy('finalapp:profile')

    def form_valid(self, form):
      form.instance.author = self.request.user
      form.save()
      print(self.request.user)
      return HttpResponseRedirect('/finalapp')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['userp'] = register.objects.filter(user_id = self.request.user.id)
        return context


class UserView(LoginRequiredMixin,CreateView):
    fields = ('date_of_birth','gender','profile_pic','hometown','education_details','interested_in','marital_status','worked_at','about_you')
    model=register
    # template_name = 'menu/order_form.html'
    # def get_object(self):
    #     return register.objects.get(id=self.request.GET.get('pk'))

class registerUpdateView(UpdateView):
    model = register
    fields = ['date_of_birth','gender','hometown','education_details','interested_in','marital_status','worked_at','about_you','profile_pic']
    template_name = 'finalapp/register_form.html'
    success_url = reverse_lazy('finalapp:user_profile')



@login_required
def logout(request):
    logout_view(request)
    return HttpResponseRedirect('/')
def users(request):
    ab = register.objects.all()
    return render(request,'users.html',{'u':ab})

def follow(request):
    loginid = request.user.id
    followid = request.GET.get('id')
    a = [loginid, followid]
    if(followUsers.objects.filter(follower=loginid,following=followid).count()==0):

        data = followUsers(follower=loginid,following=followid )
        data.save()
        data.is_friend=True
        data.save()
        print("Saved Successfully")
    else:
        data = followUsers(follower=loginid,following=followid )
        data.is_friend=False
        data.save()
        followUsers.objects.filter(follower=loginid,following=followid).delete()
        print("Already Exists and Deleted")
    return HttpResponseRedirect('/finalapp/')

def friends(request):
    data = followUsers.objects.filter(follower__contains=request.user.id)
    userp = register.objects.filter(user_id = request.user.id)
    friend_list = []
    dict={}
    for i in data:
        dict={}
        # print("follower",i.follower)
        # print("f",i.following)
        loginid = request.user.id
        uid=i.following
        friends = User.objects.get(pk=uid)
        friends2 = register.objects.get(user_id=uid)
        dict['id']=friends.id
        dict['un']=friends.username
        dict['email']=friends.email
        dict['fn']=friends.first_name
        dict['lnm']=friends.last_name
        dict['lg']=friends.last_login
        if(followUsers.objects.filter(follower=loginid).count()==0):
            dict['btt'] = 'f'
        else:
            dict['btt'] = 'u'
        dict['pp']=friends2.profile_pic
        friend_list.append(dict)
    # print(friend_list)
    total=len(friend_list)
    return render(request,'friends.html',{'data':data,'friendList':friend_list,'total':total,'userp':userp})

    return render(request,'friends.html',{'data':data})
def save_message_ajax(request):
    if request.method == "POST":
        sndr = request.user.id
        rcvr = request.POST.get('rcvr')
        message = request.POST.get('message')
        message_detail = inbox(sender=sndr, receiver=rcvr,message=message)
        message_detail.status=True
        message_detail.save()
        print('saved successfully')
        return HttpResponse("Success")
    ## Function End
def show_message_all(request):
    if request.method == "POST":
        rcvr = request.POST.get('rcvr')
        sndr = request.POST.get('sndr')
        sent_mszs = inbox.objects.filter(sender=sndr,receiver=rcvr)|inbox.objects.filter(sender=rcvr,receiver=sndr).order_by('-created_at')
        serialized_obj = serializers.serialize('json',sent_mszs)

finalproject/finalapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from finalapp.form import registerForm

# Create your views here.
def index(request):
  return render(request,'index.html')
 def registeration(request):
  return render(request,'registeration.html')

finalapp/templates/finalapp/inbox_list.html
{% extends "dashboard.html" %}
{% block body_block %}
    {% for i in post_list %}
        <p style='color:red;'>{{ i.sender }}</p>
    {% endfor %}
    <!-- {{ inbox_list }} -->
{% endblock %}

finalapp/templates/finalapp/post_confirm_delete.html
{% extends "dashboard.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h4>Are, You sure want to delete <span class='text-danger'>{{post.title}}</span> ?</h4>
        <p>After Deleting, it will not able to:</p>
        <ul>
          <li>It will not recovered anyway</li>
          <li>Your Friends cannot see this </li>
        </ul>
        <form  method="post">
          {% csrf_token %}
          <input type="submit" name="confirm" value="Yes, I am Sure" class='btn btn-danger'/>
          <a href="{% url "finalapp:post_detail" pk=post.id%}">Cancel</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

finalapp/templates/finalapp/post_detail.html
{% extends "dashboard.html"%}
{% block body_block %}

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 bg-info p-5">
      <div class="row ">
        <div class="col-md-4">

          <img src="/media/{{post_detail.image }}" height=200 width=200 alt="No Image">
        </div>
        <div class="col-md-8 ">
          
          <h4 class='display-4'>{{post_detail.title }}</h4>
          <p>{{post_detail.text}}</p>
          <small class='bg-light p-1'><i class="far fa-clock"></i> {{post_detail.create_date}}</small>
        </div>
      </div>
      <div class="col-md-12 text-center mt-4 mx-auto">
        <a href="#"></a>
        <a href="{% url "finalapp:post_update" pk=post_detail.pk %}" class='btn btn-warning'><i class="fas fa-edit"></i> Update</a>
        <a href="{% url "finalapp:post_delete" pk=post_detail.pk %}" class='btn btn-danger'><i class="fas fa-trash-alt"></i> Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock%}

finalapp/templates/finalapp/post_form.html
{% extends "dashboard.html"%}
{% block mycss %}
<style>
  #id_title{
    border:none;
  }
</style>
{% endblock %}
{% block body_block %}
{% load bootstrap4 %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h2 style='font-family:cursive;'>Create Post</h2>
    </div>
    <div class="col-md-6 mx-auto" style='background:rgba(64,126,255,0.5)'>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}

        <input type="submit" name="" value="Post" class='btn btn-primary'>
      </form>
    </div>
  </div>
</div>

{% endblock%}

finalapp/templates/finalapp/post_list.html
{% extends "dashboard.html"%}
{% block body_block %}

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class='card-columns'>
          {% for post in post_list %}
          <div class='card'>
            
                <div class='card-head'>
                    <img src="/media/{{post.image}}" height=200 width=100% alt="No Image">
                </div>
                <div class='card-body'>
                  <p class='text-primary pb-0'>{{post.title}}
                    <a href="/finalapp/{{ post.id }}" class='float-right' title='View Post'><i style='font-size:30px;' class="far fa-eye"></i> </a>
                  </p>
                    <small>Published at: {{post.create_date}}</small>
                </div>

          </div>
        {% endfor %}
      </div>
    </div>
  </div>

</div>

{% endblock%}

finalapp/templates/finalapp/register_form.html
{% load staticfiles %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>FRIENDS ZONE</title>
     <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css"%}">
     <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
     <style>
      .bootstrap4-multi-input{
        display: none;
      }
      label[for='id_profile_pic']{
        display: none;
      }
     </style>
     <script>
       $(function(){
         $('#uploadfile').click(function(){
           $('#id_profile_pic').click();
         });
       });
     </script>
  </head>
  <body>
    <div class="container-fluid" >


<div class="row p-4" style="background-image:url('{% static 'images/hd4.jpg'%}');background-size:100% 100%;">
<div class="col-md-6 mx-auto p-4" style="margin-left:300px; background-color:#cbcfd3;">
  <h2>Edit Profile</h2>
  <form method="post" enctype="multipart/form-data" class='UserForm'>
    {% csrf_token %}
    {% bootstrap_form form %}
    Profile Pic : <button type='button' class="btn btn-info" id='uploadfile'>Choose File</button><br/>
    <hr>
    <input type="submit" class='btn btn-primary btn-block mt-3' name="" value="Update">
  </form>
</div>
</div>


    </div>
  </body>
</html>